server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/sistema_login
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto=update
